---
title: "CV"
format:
  html:
    toc: true
  #pdf:
    #author: Owais Raza
    #pdf-engine: pdflatex
    
css: cv.css
---

## EDUCATION

### [Tehran University of Medical Sciences]{style="color:#E95420"}

**Ph.D. in Epidemiology** [2018]{.cvdate}

-   <b>*Thesis Title:*</b> Application of Geographically Weighted Analysis to Determine Association Between Socioeconomic Status and Childhood Morbidity in East Africa.\
-   <b>*GPA:*</b> 18.68/20\
-   <b>*Award:*</b> Diamond Merit-Based Tuition Waiver Scholarship

### [Ziauddin University]{style="color:#E95420"}

**MBBS** [2005]{.cvdate}

## EXPERIENCE

### [**BMY Health, Canada**]{style="color:#E95420"}

*Research Mentor* [Jul 2024 --- Present]{.cvdate}

-   Conducting data analysis workshops (using SPSS & STATA) for multiple rounds of internship program in collaboration with BMY Health (Pakistan).

-   Member of Research Ethic Board to oversee ethical compliance.

### [**BMY Health, Pakistan**]{style="color:#E95420"}

*Senior Researcher* [Jun 2024 --- Present]{.cvdate}

-   Served as Director of the Research Internship Program from December 2024 to March 2025, overseeing intern mentorship and training.

-   Developing training modules and fostering a research-focused learning environment.

-   Assessing the goals of interns in the start of the internship and providing advice and encouragement for supporting their research goals.

-   Offering constructive intellectual input to assist interns in the ideation and execution of their research projects.

### [**School of Public Health, Dow University of Health Sciences, Karachi (PK)**]{style="color:#E95420"}

*Assistant Professor* [Feb 2020 --- Jul 2024]{.cvdate}

-   Developed and implemented creative curricula for public health courses.

-   Taught undergraduate and postgraduate students in epidemiology, biostatistics, and research methodology.

-   Mentored students and enhanced research quality by supervising and evaluating theses.

### [**Research and Training Wing, PPHI Sindh, Karachi (PK)**]{style="color:#E95420"}

*Deputy Director (Research)* [Nov 2018 --- Jan 2020]{.cvdate}

-   Directed research initiatives across 22 districts, leveraging DHIS data to inform program planning, improve reporting accuracy, and support evidence-based decision-making.

-   Conducted healthcare facility assessment projects and led a warehouse assessment across all 22 districts.

-   Oversaw key institutional studies, including A Report on Cesarean Section Audit and Warehouse Assessment of PPHI Sindh.

-   Established the Institutional Review Board (IRB) to ensure ethical research practices across all projects.

### [**Department of Epidemiology and Biostatistics, School of Public Health, Tehran University of Medical Sciences, Tehran (IR)**]{style="color:#E95420"}

*Teaching Assistant* [Apr 2014 --- SEP 2017]{.cvdate}

-   Supervised two rounds of Community Assessment Program based on North Carolina Community Health Assessment as a part of MPH program.

-   Facilitated MPH students in Research Methodology & Epidemiology courses.

-   Conducted SPSS, STATA & R workshops for PhD candidates.

### [**Non-Communicable Diseases Research Center, Tehran University of Medical Sciences, Tehran (IR)**]{style="color:#E95420"}

*Research Assistant* [May 2013 --- Dec 2014]{.cvdate}

-   Worked with PIs to coordinate quantitative research on maternal & child health issues.

-   Participated in developing and published study protocol for national & sub-national burden of maternal conditions in Iran.

### [**Department of Community Health Sciences, Ziauddin University, Karachi (PK)**]{style="color:#E95420"}

*Lecturer* [Feb 2008 --- Sep 2012]{.cvdate}

-   Facilitated courses on Biostatistics and Epidemiology to medical students.

-   Conducted Problem – Based learning (PBL), small group sessions and lectures.

-   Supervised research projects of third- and fourth-year medical students.

-   Conducted SPSS Workshop for medical students.

## Skills

-   **R/RStudio**
-   **STATA**
-   **SPSS**
-   **DAGitty**
-   **ArcGIS**
-   **Data Visualization**

<a href="CV.pdf" download class="floating-btn">📄 Download CV</a>
