---
title: "Publications"
format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
---

- Lodhi FS, Rabbani U, Khan AA, **Raza O**, Holakouie-Naieni K, Yaseri M, Farooq U, Montazeri A. Factors associated with quality of life among joint and nuclear families: a population-based study. BMC Public Health. 2021 Dec;21(1):1-2.

- Balikuddembe JK, Ardalan A, Stephen KM, **Raza O**, Khorasani-Zavareh D. Risk factors associated with road traffic injuries at the prone-areas in Kampala city: a retrospective cross-sectional study. Journal of Injury and Violence Research. 2021 Jan;13(1):13.

- **Raza O**, Mansournia MA, Foroushani AR, Holakouie-Naieni K. Exploring spatial dependencies in the prevalence of childhood diarrhea in Mozambique using global and local measures of spatial autocorrelation. Medical Journal of the Islamic Republic of Iran. 2020;34:59.

- **Raza O**, Mansournia MA, Foroushani AR, Holakouie-Naieni K. Geographically Weighted Regression Analysis: A Statistical Method to Account for Spatial Heterogeneity. Archives of Iranian Medicine (AIM). 2019;22(3).

- Memon J, Holakouie-Naieni K, Majdzadeh R, Yekaninejad MS, Garmaroudi G, **Raza O**, et al. Knowledge, attitude, and practice among mothers about newborn care in Sindh, Pakistan. BMC Pregnancy and Childbirth. 2019;19(1):329.

- Lodhi FS, Khan AA, **Raza O**, Zaman TU, Farooq U, Holakouie-Naieni K. Level of satisfaction and its predictors among joint and nuclear family systems in District Abbottabad, Pakistan. Medical journal of the Islamic Republic of Iran. 2019;33:59.

- **Raza O**, Lodhi FS, Morasae EK, Majdzadeh R. Differential achievements in childhood immunization across geographical regions of Pakistan: analysis of wealth-related inequality. International Journal for Equity in Health. 2018;17(1):122.

- Holakouie-Naieni K, **Owais R**, Nematollahi S, Mensah LE, Memon J, Mhajabin S. Knowledge, Attitude, Practice of Dengue Fever and Its Related Factors among International Students at Tehran University of Medical Sciences. Iranian Journal of Public Health. 2018;47(11):1777-9.

- Abdullahi KO, Holakouie-Naieni K, FOROUSHANI AR, Ahmadnezhad E, **Raza O**, Nematollahi S. Knowledge, Attitude, and Practice Regarding Ebola Virus Disease and Related Factors among International Students of Tehran University of Medical Sciences, 2015. Iranian Journal of Public Health. 2018;47(5):775.

- Rahaman K, Majdzadeh R, Naieni K, **Raza O**. Comorbidities and care practices of diabetic patients. Austin J Public Health Epidemiol. 2017;4(2):1059.

- Lodhi FS, **Raza O**, Montazeri A, Nedjat S, Yaseri M, Holakouie-Naieni K. Psychometric properties of the Urdu version of the World Health Organization's quality of life questionnaire (WHOQOL-BREF). Medical Journal of the Islamic Republic of Iran. 2017;31:129.

- Khazaei S, Rezaeian S, Baigi V, Saatchi M, Molaeipoor L, Khazaei Z, et al. Incidence and pattern of tuberculosis treatment success rates in different levels of the human development index: a global perspective. Southern African Journal of Infectious Diseases. 2017;32(3):100-4.

- Kh. Shafiur Rahaman RM, Kourosh Holakouie Naieni, **Raza O**. Knowledge, Attitude and Practices (KAP) Regarding Chronic Complications of Diabetes among Patients with Type 2 Diabetes. Int J Endocrinol Metab. 2017.

- Balikuddembe JK, Ardalan A, Khorasani-Zavareh D, Nejati A, **Raza O**. Weaknesses and capacities affecting the Prehospital emergency care for victims of road traffic incidents in the greater Kampala metropolitan area: a cross-sectional study. BMC Emergency Medicine.2017;17(1):29.

- Safiri S, Haghdoost AA, Hashemi F, Amiri S, **Raza O**, Sadeghi-Bazargani H. Association between adult attention deficit hyperactivity disorder and helmet use among motorcycle riders. Trauma Mon. 2016;21(2):e21066. doi:10.5812/traumamon.21066.

- Holakouie-Naieni K, Ahmadvand A, **Raza O**, Assan A, Elduma AH, Jammeh A, Kamali AS, Kareem AA, Muhammad FM, Sabahat H, Abdullahi KO, Saeed RA, Saeed SN. Assessing the knowledge, attitudes, and practices of students regarding Ebola virus disease outbreak. Iran J Public Health. 2015;44(12):1670-6.

- Hajizadeh S, Vahid Dastjerdi M, Moradi-Lakeh M, Khajavi A, Farzadfar F, Zandian E, **Raza O**, Tehrani FR, Farzadfar F. The trend of national and subnational burden of maternal conditions in Iran from 1990 to 2013: the study protocol. Arch Iran Med. 2014;17(3):198–203.

- Shoaib B, Ali M, Danish SH, **Raza O**. Human Immunodeficiency Virus, Hepatitis B and C: Barbers knowledge and their Practices. Infectious Diseases Journal of Pakistan. 2012;40(17):628.